### ISSUE TITLE
Unknown plugin "add-module-exports" specified in ......./react-keyboard-event-handler

### ISSUE THREAD

**Issue by amaljose96** [linsight/react-keyboard-event-handler#2]
`import KeyboardEventHandler from 'react-keyboard-event-handler';`

Causes an error 

```
error: bundling failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/amaljose/ReactProjects/Hello360/node_modules/react-keyboard-event-handler/.babelrc" at 0, attempted to resolve relative to "/Users/amaljose/ReactProjects/Hello360/node_modules/react-keyboard-event-handler"
    at /Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/amaljose/ReactProjects/Hello360/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transform (/Users/amaljose/ReactProjects/Hello360/node_modules/metro-bundler/src/transformer.js:133:11)
```

**Comment by dlin-me** [comment]
Could you try the new version 1.3.1.

What I did was to remove .babelrc from the published package.

**Comment by dlin-me** [comment]
Closing it now as not further info is available.
